commerce/auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    ## List views
    path("categories", views.categories, name="categories"),
    path(
        "categories/<str:category>",
        views.ListingsByCategoryListView.as_view(),
        name="listings-by-category",
    ),
    path("listings/", views.ListingsListView.as_view(), name="listings"),
    path(
        "listings/<int:pk>", views.ListingDetailView.as_view(), name="listing-details"
    ),
    ## Watchlist
    path("watchlist", views.WatchlistListView.as_view(), name="listings-watchlist"),
    path("watchlist/add/<int:id>", views.watchlist_add, name="watchlist-add"),
    path("watchlist/remove/<int:id>", views.watchlist_remove, name="watchlist-remove"),
    ## Create/Edit
    path("listing/new", views.listing_new, name="listing-new"),
    path("listing/<int:pk>/edit", views.listing_edit, name="listing-edit"),
    ## Comments and Replies
    # id of a listing
    path(
        "listing/comment/<int:listing_id>",
        views.listing_comment,
        name="listing-comment",
    ),
    # id of a comment
    path("listing/reply/<int:comment_id>", views.listing_reply, name="listing-reply"),
    ## Listings owned
    path("my-listings", views.ListingsOwnedListView.as_view(), name="listings-owned"),
    ## Bidding
    # get min bid amount and current price
    path(
        "listing/<int:listing_id>/get-min-bid",
        views.listing_get_min_bid,
        name="listing-get-min-bid",
    ),
    # set bid amount
    path(
        "listing/<int:listing_id>/set-bid",
        views.listing_set_bid,
        name="listing-set-bid",
    ),
    # close listing
    path(
        "listing/<int:listing_id>/close-listing",
        views.listing_close,
        name="listing-close",
    ),
    ## Bid History
    path(
        "listing/<int:listing_id>/bid-history",
        views.listing_bid_history,
        name="listing-bid-history",
    ),
    ## Login/Logout/Register urls
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
]

commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [path("admin/", admin.site.urls), path("", include("auctions.urls"))]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commerce/auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse  # Used to generate URLs by reversing the URL patterns
from django.utils import timezone

from PIL import Image


class User(AbstractUser):

    ## usage:
    #   user.watchlist.add(listing_id)
    #   user.watchlist.remove(listing_id)
    #   user.watchlist.clear()  --> removes all the watchlist for a given user
    watchlist = models.ManyToManyField(
        "Listing", blank=True, related_name="user_watchlist"
    )

    watchlist_item_count = models.IntegerField(default=0)

    def __str__(self):
        return self.username

    def get_watchlist(self):
        return self.watchlist.all()

    def get_watchlist_by_recently_added(self):
        return self.watchlist.all().reverse()


class Category(models.Model):
    """Model representing an Auction Listing category"""

    category_string = models.CharField(
        max_length=300,
        unique=True,
        help_text="Enter dashed representation of the category name",
        null=True,
        blank=True,
    )

    category_name = models.CharField(
        max_length=200, unique=True, help_text="Enter listing category"
    )

    def __str__(self):
        return self.category_name

    class Meta:
        ordering = ["category_string"]


class Listing(models.Model):
    """Model representing an Auction Listing"""

    seller = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="seller_listings"
    )

    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        null=True,
        help_text="Select a category for this listing",
    )

    title = models.CharField(max_length=300)

    description = models.TextField(
        max_length=1000, help_text="Enter a brief description of the listing"
    )

    starting_price = models.DecimalField(
        max_digits=8, decimal_places=2, null=True, blank=True
    )

    # remember to set current_price to starting_price in the views
    current_price = models.DecimalField(
        max_digits=8, decimal_places=2, null=True, blank=True
    )

    date_created = models.DateTimeField(default=timezone.now)

    listing_status = [
        ("active", "Active listing"),
        ("closed", "Closed listing"),
    ]

    status = models.CharField(
        max_length=6,
        choices=listing_status,
        default="active",
        help_text="Listing status",
    )

    was_edited = models.BooleanField(default=False)

    edit_count = models.IntegerField(default=0)

    bidding_starts = models.DateTimeField(default=timezone.now, blank=True, null=True)

    # set manually upon closing the listing
    bidding_ended = models.DateTimeField(blank=True, null=True)

    duration = models.DurationField(
        default=timezone.timedelta(days=0),
        null=True,
        blank=True,
        help_text="Enter the duration of the listing",
    )

    bid_count = models.IntegerField(default=0)

    watcher_count = models.IntegerField(default=0)

    winner = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="won_listings",
    )

    # imageURL = models.URLField(
    #     max_length=500, blank=True, help_text="Enter an image URL"
    # )

    image = models.ImageField(
        default="default.jpg", upload_to="product_pics", null=True
    )

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        """Returns the URL to access a detail record for this listing."""
        # return reverse("listing-detail", args=[str(self.id)])
        return reverse("listing-detail", kwargs={"pk": self.pk})

    ## Used formatting directly in template instead: <Posted on {{ value|date:"N d, Y - h:i A (T)" }}>
    # def get_readable_date(self):
    #     """Returns human readable creation date"""
    #     est = tz("US/Eastern")
    #     date = self.date_created.astimezone(est)
    #     format = "%b. %d, %Y - %I:%M %p (%Z)"
    #     return f"Posted on {date.strftime(format)}"

    class Meta:
        ordering = ["status", "-date_created"]

    # re-do this based on bidding_starts, duration, and current date
    @property
    def is_expired(self):
        """Determines if the listing is expired based on date_created, duration and current date."""
        # Note: whether duration is 0 is being verified. If duration is 0 the listing will be closed manually, so it is never expired
        if self.duration > timezone.timedelta(minutes=0):
            return bool(timezone.now() > (self.bidding_starts + self.duration))
        else:
            return False

    @property
    def listing_ends(self):
        """Returns when it ends or, if it does not end, returns 'No date set.'"""
        if self.duration > timezone.timedelta(minutes=0):
            return self.bidding_starts + self.duration
        else:
            return "No date set"

    # resizing the image on save (thumbnail() maintains aspect ratio)
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 500 or img.width > 500:
            output_size = (500, 500)
            img.thumbnail(output_size)
            img.save(self.image.path)

    def get_listing_comments(self):
        """Returns comments for the listing ordered by most recent"""
        return self.listing_comments.order_by("-date")

    def get_min_bid_amount(self):
        """Returns the min bid amount possible given the current price"""
        if self.bid_count == 0:
            # the initial bid can be equal to starting price
            return self.starting_price

        else:
            current_price = float(self.current_price)

            if 0.01 <= current_price <= 0.99:
                return current_price + 0.05
            if 1.00 <= current_price <= 4.99:
                return current_price + 0.25
            if 5.00 <= current_price <= 24.99:
                return current_price + 0.50
            if 25.00 <= current_price <= 99.99:
                return current_price + 1.00
            if 100.00 <= current_price <= 249.99:
                return current_price + 2.50
            if 250.00 <= current_price <= 499.99:
                return current_price + 5.00
            if 500.00 <= current_price <= 999.99:
                return current_price + 10.00
            if 1000.00 <= current_price <= 2499.99:
                return current_price + 25.00
            if 2500.00 <= current_price <= 4999.99:
                return current_price + 50.00
            if current_price >= 5000.00:
                return current_price + 100.00


class Bid(models.Model):

    bidder = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_bids")

    listing = models.ForeignKey(
        Listing, on_delete=models.CASCADE, related_name="listing_bids"
    )

    amount = models.DecimalField(max_digits=8, decimal_places=2, null=True, blank=True)

    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.bidder.username}: {self.amount}"


class Comment(models.Model):

    user = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, related_name="user_comments"
    )

    listing = models.ForeignKey(
        Listing, on_delete=models.CASCADE, related_name="listing_comments"
    )

    comment = models.TextField(max_length=1000, help_text="Enter a comment")

    date = models.DateTimeField(default=timezone.now)

    replies = models.ManyToManyField(
        "Comment", blank=True, related_name="comment_replies"
    )

    comment_status = [
        ("comment", "This is a comment"),
        ("reply", "This is a reply"),
    ]

    status = models.CharField(
        max_length=7,
        choices=comment_status,
        default="comment",
        help_text="Comment status",
    )

    reply_to = models.CharField(max_length=150, blank=True)

    def __str__(self):
        return f"({self.date.astimezone()}) {self.user.username}: {self.comment}"

    def get_comment_replies(self):
        """Returns replies for a comment ordered by least recent"""
        return self.comment_replies.order_by("date")

commerce/auctions/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.password_validation import (
    validate_password,
    get_default_password_validators,
)
from django.utils.translation import gettext_lazy as _

from django.forms import ModelForm
from .models import User, Listing, Category
from django.utils import timezone
import datetime
import re


## Registration and Login


class RegisterUserModelForm(ModelForm):
    class Meta:
        model = User
        fields = ["username", "email", "password"]

    def clean_password(self):
        data = self.cleaned_data["password"]

        # raises ValidationError, or None if valid
        validate_password(data, password_validators=get_default_password_validators())

        return data


class LoginUserForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(max_length=100)


## Create and Edit Listing


class ListingModelForm(ModelForm):
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        empty_label="Select a category",
        widget=forms.Select(attrs={"class": "form-select text-secondary"}),
    )

    class Meta:
        model = Listing
        fields = [
            "title",
            "description",
            "category",
            "starting_price",
            # optional:
            "bidding_starts",
            "duration",
            "image",
        ]

    def clean_starting_price(self):
        """Starting price has to be positive and less than 100,000.00"""
        data = self.cleaned_data["starting_price"]
        PRICE_OVERFLOW = 100000

        if not data:
            raise ValidationError(_("Cannot be empty or $0."))

        if not (0 < data <= PRICE_OVERFLOW):
            raise ValidationError(
                _(
                    "Invalid amount. Starting price has to be higher than $0 and less than $100,000.00"
                )
            )

        return data

    def clean_duration(self):
        """Duration cannot be greater than 7 days"""
        data = self.cleaned_data.get("duration", "")

        if data:
            if data > datetime.timedelta(days=3):
                raise ValidationError(
                    _("Invalid duration. The duration cannot be greater than 3 days.")
                )
            if data < datetime.timedelta(days=0):
                raise ValidationError(
                    _("Invalid duration. The duration cannot be less than 0.")
                )
        return data

    def clean_bidding_starts(self):
        """Starting date cannot be in the past or greater than 3 days ahead"""
        data = self.cleaned_data.get("bidding_starts", "")

        min = timezone.make_aware(
            datetime.datetime.now() - datetime.timedelta(hours=1),
            timezone.get_default_timezone(),
        )

        max = timezone.make_aware(
            datetime.datetime.fromisoformat(
                (datetime.date.today() + datetime.timedelta(days=3)).isoformat()
            )
            + datetime.timedelta(hours=23, minutes=59)
        )

        if data:
            # Check if a date is not in the past.
            if data < min:
                raise ValidationError(
                    _("Invalid date. Starting date cannot be in the past.")
                )

            # Check if a date is in the allowed range (max. 3 days from today).
            if data > max:
                raise ValidationError(
                    _("Invalid date. Starting date cannot be more than 3 days ahead.")
                )

        return data

commerce/auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Active Listings</h2>

    TODO

    <button type="button" class="btn btn-outline-primary d-lg-none" data-bs-toggle="modal" data-bs-target="#modal">
      Filter
    </button>
      
    <div id="modal fade" class="modal" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">

            </div>
          </div>
        </div>
    </div>
{% endblock %}

{% block additional_js %}

{% endblock %}

commerce/auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Auctions{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
        <link href="{% static 'auctions/css/styles.css' %}" rel="stylesheet">
    </head>
    <body class="">
    <div class="container-fluid">

    <header class="bg-light rounded-1 py-3 mb-3 border-bottom shadow-sm border-4">
    <div class="container-fluid wrapper-all">
        <h1>Auctions</h1>
        <div class="text-secondary" style="--bs-text-opacity: .8">
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>

        <nav class="navbar navbar-expand-sm">
            <div class="container-fluid">
                <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse flex-wrap justify-content-between" id="navbarSupportedContent">
                    <!-- <hr class="d-sm-none"> -->
                    <div class="d-sm-none py-3"></div>
                    <ul class="navbar-nav mt-3 d-flex flex-wrap">
                        <li class="nav-item nav-item-responsive-margin">
                            <a class="mb-1 nav-link btn btn-light shadow-sm link-secondary border border-1 {% if cue == 'all' %} text-decoration-underline {% endif %}" href="{% url 'listings' %}">Active Listings</a>
                        </li>
                        <li class="nav-item nav-item-responsive-margin">
                            <a class="mb-1 nav-link btn btn-light shadow-sm link-secondary border border-1 {% if cue == 'category' %} text-decoration-underline {% endif %}" href="{% url 'categories' %}">Categories</a>
                        </li>
                        {% if user.is_authenticated %}
                            <li class="nav-item nav-item-responsive-margin">
                                <a class="mb-1 nav-link btn btn-light shadow-sm link-secondary border border-1 {% if cue == 'watchlist' %} text-decoration-underline {% endif %}" href="{% url 'listings-watchlist' %}">
                                    Watchlist <small><span class="badge shadow-sm text-bg-warning js-watchlist-badge" style="min-width: 1.8rem;">{{ user.watchlist_item_count }}</span></small>
                                </a>
                            </li>
                        {% else %}
                            <li class="nav-item nav-item-responsive-margin" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-animation="false" title="Log in to use feature">
                                <a class="mb-1 nav-link btn btn-light shadow-sm link-secondary border border-1 disabled" href="">Watchlist</a>
                            </li>
                        {% endif %}
                        {% if user.is_authenticated %}
                            <li class="nav-item nav-item-responsive-margin">
                                <a class="mb-1 nav-link btn btn-light shadow-sm link-secondary border border-1 {% if cue == 'create' %} text-decoration-underline {% endif %}" href="{% url 'listing-new' %}">Create Listing</a>
                            </li>
                        {% else %}
                            <li class="nav-item nav-item-responsive-margin" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-animation="false" title="Log in to use feature">
                                <a class="mb-1 nav-link btn btn-light shadow-sm link-secondary border border-1 disabled" href="">Create Listing</a>
                            </li>
                        {% endif %}
                        {% if user.is_authenticated %}
                            <li class="nav-item nav-item-responsive-margin">
                                <a class="mb-1 nav-link btn btn-light shadow-sm link-secondary border border-1 {% if cue == 'owned' %} text-decoration-underline {% endif %}" href="{% url 'listings-owned' %}">My Listings</a>
                            </li>
                        {% else %}
                            <li class="nav-item nav-item-responsive-margin" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-animation="false" title="Log in to use feature">
                                <a class="mb-1 nav-link btn btn-light shadow-sm link-secondary border border-1 disabled" href="">My Listings</a>
                            </li>
                        {% endif %}
                    </ul>
                    <ul class="navbar-nav section-login mt-3">
                        {% if user.is_authenticated %}
                            <li class="nav-item nav-item-responsive-margin">
                                <a class="mb-1 nav-link btn btn-light shadow-sm link-secondary rounded-pill border border-1" href="{% url 'logout' %}">Log Out</a>
                            </li>
                        {% else %}
                            <li class="nav-item nav-item-responsive-margin">
                                <a class="mb-1 nav-link btn btn-light shadow-sm link-primary rounded-pill border border-1" href="{% url 'login' %}?next={{ request.path }}">Log In</a>
                            </li>
                            <li class="nav-item nav-item-responsive-margin">
                                <a class="mb-1 nav-link btn btn-light shadow-sm link-primary rounded-pill border border-1" href="{% url 'register' %}">Register</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

    </div>
    </header>

    <main class="container-fluid wrapper-all">
        {% if logout %}
        <div class="alert alert-info d-flex align-items-center border-0 border-start border-5 border-info" role="alert">
            <i class="bi flex-shrink-0 me-2 bi-check-circle"></i>
            <div>Logged out successfully.</div>
        </div>
        {% endif %}

        {% block body %}
        {% endblock %}
    </main>

    <footer class="bg-light rounded-1 py-3 mt-5 border-top shadow border-4" style="height: 30vh;">
    <div class="container-fluid wrapper-all">


    </div>
    </footer>

    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="{% static 'auctions/main.js' %}"></script>
        {% block additional_js %}
        {% endblock %}
    </body>
</html>

commerce/auctions/templates/auctions/listing_form_edit.html
{% extends "auctions/listing_form_new.html" %}

{% block heading_listing %}
    Edit Listing
{% endblock %}

{% block warning_listing %} 
    <div class="alert alert-warning d-flex gap-3 border border-warning border-2" role="alert">
        <span class="fs-2"><i class="bi bi-exclamation-diamond"></i></span>
        <span class="">Editing the listing will reset <strong>bids</strong>, <strong>comments</strong>, <strong>starting date</strong>, and <strong>duration</strong>.
            <br>
            Additionally, the listing will be marked as edited in any Watchlist and details page.</span>
    </div>
{% endblock %}

{% block image_current %}
    <div class="form-text pt-1">Currently: <a class="text-break link-primary text-decoration-none" href="{{ listing.image.url }}" target="_blank">{{imageName}}</a></div>
{% endblock %}

commerce/auctions/templates/auctions/listing_form_new.html
{% extends "auctions/layout.html" %}
{% load static %}

{% block body %}

<h2>{% block heading_listing %}New Listing{% endblock %}</h2>
<div class="py-3"></div>

<div class="list-unstyled container-fluid border shadow rounded py-3 mb-5">

    {% block warning_listing %} {% endblock %}

    {% if form.non_field_errors %}
        <div class="alert alert-warning d-flex align-items-center border-0 border-start border-5 border-warning" role="alert">
            <i class="bi flex-shrink-0 me-2 bi-exclamation-diamond"></i>
            <div>{{ form.non_field_errors }}</div>
        </div>
    {% endif %}

    <form method="post" enctype="multipart/form-data" class="js-create-form">
        {% csrf_token %}
        <fieldset class="form-group p-3">
            <legend class="mb-4">Required Information</legend>
            <div class="mb-4">
                <label for="title" class="form-label">Title</label>
                <div class="text-danger css-list-unstyled">{{ form.title.errors }}</div>
                <input type="text" class="form-control" id="title" name="title" {% if title %} value="{{title}}" {% endif %} required autofocus>
                <div class="form-text">Provide a title for the product.</div>
            </div>
            <div class="mb-4">
                <label for="description" class="form-label">Description</label>
                <div class="text-danger css-list-unstyled">{{ form.description.errors }}</div>
                <textarea class="form-control" name="description" id="description" cols="30" rows="5" required placeholder="{{ placeholder_description }}">{% if description %}{{description}}{% endif %}</textarea>
                <div class="form-text">Provide product details (i.e.: dimensions and condition).</div>
            </div>
            <div class="mb-4" style="max-width: 18.75rem;">
                <label class="form-label">Category</label>
                <div class="text-danger css-list-unstyled">{{ form.category.errors }}</div>
                {{ form.category }}
            </div>
            <div class="mb-4" style="max-width: 18.75rem;">
                <label for="id_starting_price" class="form-label">Starting price</label>
                <div class="text-danger css-list-unstyled">{{ form.starting_price.errors }}</div>
                <div class="input-group">
                    <span class="input-group-text">$</span>
                    <input type="tel" name="starting_price" {% if starting_price %} value="{{starting_price}}" {% endif %} required placeholder="Initial bidding price" id="id_starting_price" pattern="^\d*\.?\d*$" onclick="this.value=''" class="form-control">
                </div>
                <div class="form-text">Enter a dollar amount.</div>
            </div>
        </fieldset>

        <fieldset class="form-group p-3">
            <legend class="mb-4">Optional Info</legend>
            <div class="mb-4">
                <label for="formFile" class="form-label">Product Image</label>
                {% if imageReminder %}
                <div class="text-danger css-list-unstyled"><ul><li>{{imageReminder}}</li></ul></div>
                {% endif %}
                <div class="text-danger css-list-unstyled">{{ form.image.errors }}</div>
                <input class="form-control text-secondary" type="file" id="formFile" name="image" accept="image/*" {% if imageName %} value="{{imageName}}" {% endif %}>
                {% block image_current %}{% endblock %}
            </div>
        </fieldset>

        <fieldset class="form-group p-3">
            <legend class="mb-4">Optional Settings</legend>
            <div class="mb-4" style="max-width: 18.75rem;">
                <label for="bidding_starts" class="form-label">Starting Date</label>
                <div class="text-danger css-list-unstyled">{{ form.bidding_starts.errors }}</div>
                <input type="datetime-local" class="form-control" id="bidding_starts" name="bidding_starts" min="{{ date.starts_min }}" max="{{ date.ends_max }}" {% if bidding_starts %} value="{{bidding_starts}}" {% endif %}>
                <div class="form-text">Specify when the listing will become active after posting it (maximum 3 days ahead from today).</div>
            </div>
            <div class="mb-4" style="max-width: 18.75rem;">
                <label for="duration" class="form-label">Duration</label>
                <div class="text-danger css-list-unstyled">{{ form.duration.errors }}</div>
                <div class="input-group">
                    <input type="number" class="form-control" id="durationValue" name="duration" min="{{ date.lasts_min }}" max="{{ date.lasts_max }}" {% if duration %} value="{{duration}}" {% endif %}>
                    <span class="input-group-text">day(s)</span>
                </div>
                <div class="form-text">
                    Specify for how long the listing will be active (1 - 3 days). 
                </div>
            </div>
            <div class="alert alert-warning" role="alert">
                Leave <strong>starting date</strong> blank if the listing should become active immediately after posting it.
            </div>
            <div class="alert alert-warning" role="alert">
                Leave <strong>duration</strong> blank if the listing should be active indefinitely until manually closed.
            </div>
        </fieldset>

        <!-- <input type="hidden" value="" name="imageFileName" id="imageFilename">
        <input type="hidden" name="duration" value="" id="duration"> -->
        <div class="form-group mx-auto w-50">
            <button type="submit" class="btn btn-outline-primary w-100">Post</button>
        </div>
    </form>

</div>
{% endblock %}

commerce/auctions/templates/auctions/listings_active_all.html
{% extends "auctions/listings_by_category.html" %}


{% block listing_heading %}
    All Active Listings
{% endblock %}

commerce/auctions/templates/auctions/listings_categories.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>All Categories</h2>

    <div class="py-3"></div>

    <ul class="list-unstyled container-fluid border shadow rounded py-3 mb-5">
    {% for category in categories %}

        <!-- <li class="p-3 mb-3 border rounded shadow-sm d-flex"> -->
        <li class="w-75 position-relative">
            <a class="p-3 mb-3 border rounded d-block text-decoration-none link-secondary css-category-item" href="{% url 'listings-by-category' category.category.category_string %}">{{ category.category.category_name }}</a>
            {% if category.available %}
            <span class="position-absolute border border-1 p-1 pt-3 fw-bold text-light css-category-tag">available</span>
            {% endif %}
        </li>

    {% empty %}
        <li>No categories</li>
    {% endfor%}
    </ul>

{% endblock %}

{% block additional_js %}

{% endblock %}

commerce/auctions/templates/auctions/listings_owned.html
{% extends "auctions/listings_by_category.html" %}
{% load static %}


{% block listing_heading %}
    My Listings
{% endblock %}


{% block customButton %}
<!-- No button next to image (Leave blank) -->

<!-- ---------------------------------------------------------------------------- -->
{% endblock %}


{% block listing_description_margin %} 
mb-5
{% endblock %}


{% block listing_status %}
    {% if listing.status == 'closed' %}
        <span class="badge text-bg-danger">Closed</span>
    {% else %}
        {% if listing.was_edited %}
        <span class="badge text-bg-warning">Edited: {{ listing.edit_count }}</span>
        {% endif %}
    {% endif %}
{% endblock %}


{% block listings_owned_custom %}
Set to start:
{% endblock %}


{% block listing_edit %}
<p class="position-absolute bottom-0 end-0">
    <a class="btn btn-outline-dark px-5" href="{% url 'listing-edit' listing.pk %}">Edit</a>
</p>
{% endblock %}


{% block customMessage %}
<div>
    {% if search_criteria %} 
        No results found. 
    {% else %} 
        No listings created. 
    {% endif %}
</div>
{% endblock %}


{% block additional_js_inherits_listings %}
    
{% endblock %}